// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      throw UnsupportedError(
        'DefaultFirebaseOptions have not been configured for web - '
        'you can reconfigure this by running the FlutterFire CLI again.',
      );
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for macos - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyD4xlnWvrZjdUbX2h_qYOJpBP7S0i-Ps2Q',
    appId: '1:954133100225:android:501a3486c79bc0a45b8640',
    messagingSenderId: '954133100225',
    projectId: 'calendar-2c4e5',
    storageBucket: 'calendar-2c4e5.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyDrmrYTOQf-5xmsfp7gj5a4R7pFbp0cifo',
    appId: '1:954133100225:ios:6f930884ce525fc15b8640',
    messagingSenderId: '954133100225',
    projectId: 'calendar-2c4e5',
    storageBucket: 'calendar-2c4e5.firebasestorage.app',
    iosBundleId: 'com.example.calendar',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyBO2VvTSfWWsudCDg0G71dvB5WCJnQr-Lo',
    appId: '1:954133100225:web:3b20426687847ed75b8640',
    messagingSenderId: '954133100225',
    projectId: 'calendar-2c4e5',
    authDomain: 'calendar-2c4e5.firebaseapp.com',
    storageBucket: 'calendar-2c4e5.firebasestorage.app',
    measurementId: 'G-LBFMC0DMBH',
  );
}
